### ISSUE TITLE
linea 51, para ahorrar tiempo y ser más productivo hubiera puesto la varibale num en vez de número

### ISSUE THREAD

**Issue by jlalvarezfernandez** [iesgrancapitan-entornos/practica-5-github-issues-FcoJavierGlez#1]
https://github.com/iesgrancapitan-entornos/practica-5-github-issues-FcoJavierGlez/blob/81b3a6874b993b7d27feb54693a16418a5afd588/ConversorDecHex.java#L51

**Comment by FcoJavierGlez** [comment]
Gracias por el comentario me encargaré de revisarlo en breve.

**Comment by jlalvarezfernandez** [comment]
ok, me gusta tu prontitud en la respuesta.

**Comment by jaimerabasco** [comment]
Solo cierras 1 issue, en lugar de los 4 que pide la práctica @FcoJavierGlez @jlalvarezfernandez

**Comment by jlalvarezfernandez** [comment]
gracias, intetare cerrarlos lo antes posible

**Comment by FcoJavierGlez** [comment]
Corregida la línea 51
