### ISSUE TITLE
simbolo innecesario

### ISSUE THREAD

**Issue by jlalvarezfernandez** [iesgrancapitan-entornos/practica-5-github-issues-FcoJavierGlez#1]
has introducido un simbolo innecesario

https://github.com/iesgrancapitan-entornos/practica-5-github-issues-FcoJavierGlez/blob/a3b016ae0ed63085933ccd8368cae36009b84ad7/ConversorDecHex.java#L34

**Comment by FcoJavierGlez** [comment]
Gracias José Luis le echo un vistazo en breve

**Comment by jlalvarezfernandez** [comment]
muchas gracias por hacerme caso

**Comment by FcoJavierGlez** [comment]
Acabo de arreglar el issue, gracias por tu colaboración.
