### ISSUE TITLE
falta descripción del parámetro

### ISSUE THREAD

**Issue by jlalvarezfernandez** [iesgrancapitan-entornos/practica-5-github-issues-FcoJavierGlez#2]
parámetro necesita descripción
https://github.com/iesgrancapitan-entornos/practica-5-github-issues-FcoJavierGlez/blob/9bad28f1fa2e33e8b76b8be23ff00bc1f2d3f434/ConversorDecHex.java#L82

**Comment by FcoJavierGlez** [comment]
Gracias José Luis voy a revisarlo ahora mismo.

**Comment by jlalvarezfernandez** [comment]
ok, compañero
