### ISSUE TITLE
falta un punto 

### ISSUE THREAD

**Issue by jlalvarezfernandez** [iesgrancapitan-entornos/practica-5-github-issues-FcoJavierGlez#3]
falta un punto
https://github.com/iesgrancapitan-entornos/practica-5-github-issues-FcoJavierGlez/blob/6b986c1fa52ff4efd286b731964b2c884e936df0/ConversorDecHex.java#L67

**Comment by FcoJavierGlez** [comment]
Gracias, me pongo con ello
