### ISSUE TITLE
falta tu tercer apellido

### ISSUE THREAD

**Issue by jlalvarezfernandez** [iesgrancapitan-entornos/practica-5-github-issues-FcoJavierGlez#4]
falta apellido

https://github.com/iesgrancapitan-entornos/practica-5-github-issues-FcoJavierGlez/blob/6b986c1fa52ff4efd286b731964b2c884e936df0/ConversorDecHex.java#L4

**Comment by FcoJavierGlez** [comment]
Lo arreglo en seguida, gracias.
